# 工作流名称，会出现在 github 的 action 标签里面作为显示
name: Deploy automatically Demo
# 定义触发执行任务事件，下面表示 push main 时会执行 jobs。
on:
  push:
    branches:
      'main'
# 定义任务
jobs:
  # 任务名称，注意：名称不能用空格
  Job_one: 
    # 使用最新的 ubuntu 环境
    runs-on: ubuntu-latest
    # 执行命令步骤
    steps:
      - name: 切换分支
        uses: actions/checkout@v2

      - name: 下载 node14 
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: 下载 bats
        run: npm install -g bats
      
      - name: 展示 bats 版本
        run: bats -v

      - name: '问候'
        id: hello
        uses: './.github/actions/hello-world-javascript-action'
        with:
          who-to-greet: 'Nick C'
      - name: '问候时间'
        run: echo "The time was ${{ steps.hello.outputs.time }}"

      - name: 获取 Github 的秘密信息，你可以将秘密信息比如密码放到 github secret 里 ，然后在这里访问，这样可以确保安全。
        env:
          vite_secret: ${{ secrets.VITE_TODO_SECRET }}
        run: echo "The secret is $vite_secret"
  Job_two:
    # 等待 Job_one 执行完在轮到我执行，如果不指定，Job_one / Job_two 会同时执行，因为默认是异步的。
    needs: Job_one
    runs-on: ubuntu-latest
    steps:
      - name: 打印
        run: echo "All finished!"
